src/Entity/TollSlips.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TollSlipsRepository")
 */
class TollSlips
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Plaza;

    /**
     * @ORM\Column(type="float")
     */
    private $Amount;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPlaza(): ?string
    {
        return $this->Plaza;
    }

    public function setPlaza(string $Plaza): self
    {
        $this->Plaza = $Plaza;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->Amount;
    }

    public function setAmount(float $Amount): self
    {
        $this->Amount = $Amount;

        return $this;
    }
}

templates/private/summary.html.twig
{% extends 'base.html.twig' %}

{% block title %}Holmes Place{% endblock %}

{% block body %}
   
    <div class="main">    
    
        <h4> Todays Date: {{ current_date }} </h4>
        <h4>{% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <p>Email: {{ app.user.email }}</p>
{% endif %}</h4>
    
    <p>The growth percentage is calculated for the last 3 entries, the last 3 are displayed below.</p>
    <div class="inlineTable">
    <table>
        <caption>Wallets</caption>
        <tr><th></th><th>Balance</th><th>Value</th><th>Growth</th>
        <tr>
            <td>Bitcoin</td>
            <td>{{ cryptoStats[0]['balance'] }}</td>
            <td>{{ cryptoStats[0]['balance'] * crypto_prices[0].btc_price }}</td>
            <td></td>
        </tr>
        <tr>
            <td>Etherium</td>
            <td>{{ cryptoStats[1].balance }}</td>
            <td>{{ cryptoStats[1].balance * crypto_prices[0].eth_price }}</td>
            <td></td>
        </tr>
        <tr>
            <td>Etherium-Savings</td>
            <td>{{ cryptoStats[3].balance }}</td>
            <td>{{ cryptoStats[3].balance * crypto_prices[0].eth_price }}</td>
            <td></td>
        </tr>
        <tr>
            <td>Rands</td>
            <td> {{ cryptoStats[2].balance }} </td>
            <td>{{ cryptoStats[2].balance }}</td>
            <td></td>
        </tr>
    </table>
      </div>      
        <div class="inlineTable">
         <table>
             <caption> Last 3 Values</caption>
        <tr>
            <th></th>
            <th>3rd</th>
            <th>2nd</th>
            <th>Cur</th>
            <th>Growth(%)</th><tr>
        <tr>         
            <td>Bitcoin</td>
            <td style="text-align:right"> {{ crypto_prices[2].btc_price }}</td>
            <td style="text-align:right"> {{ crypto_prices[1].btc_price }}</td>
            <td style="text-align:right"> {{ crypto_prices[0].btc_price }}</td>
            <td class="posGrowth"> </td>
            
            
        </tr>
        <tr>
            
            <td>Etherium</td>
            <td style="text-align:right">{{ crypto_prices[2].eth_price }}</td>
            <td style="text-align:right">{{ crypto_prices[1].eth_price }}</td>
            <td style="text-align:right">{{ crypto_prices[0].eth_price }}</td>
            <td class="posGrowth">  </td>
            
                
        </tr>
        <tr><td>Rands</td>
            <td class="posGrowth">  </td>
            <td class="negGrowth">  </td>
            <td class="posGrowth"> </td>
            <td class="negGrowth"> </td>
            
    </table>     
    </div>
        <br> <br>
    
        
            
                
<div class="inlineTable">
  {% if fuel_entries is defined %}  
  <table>
      <caption>Fuel for Current Month</caption>
      <tr><th>Date</th><th>Odometer</th><th>Liters</th><th>Cost/Liter</th><th>Amount</th><th>Location</th><th>Full Tank</th></tr>
  {% for fuelentry in fuel_entries %}
          <tr>
              <td style="text-align:right"> {{ fuelentry.date }} </td>
              <td style="text-align:right"> {{ fuelentry.odometer }} </td>
              <td style="text-align:right"> {{ fuelentry.liters }} </td>
              <td style="text-align:right"> {{ fuelentry.amount // fuelentry.liters }}</td>
              <td style="text-align:right"> {{ fuelentry.amount }} </td>
              <td style="text-align:right"> {{ fuelentry.location }} </td>
              <td style="text-align:right"> {{ fuelentry.tankfull }} </td>
           </tr>    
  {% endfor %}
  
  {% endif %}
  
  </table>
</div>
</div>
{% endblock %}